<?php

namespace Vshapovalov\Crud\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Vshapovalov\Crud\TreeableTrait;

class MenuItem extends Model
{
	use TreeableTrait;

	protected $table ='menu_items';
	protected $primaryKey ='id';

	public function resetMenuCache(){

	    if (count($itemsWithCode = MenuItem::whereNotNull('code')->get())){

            foreach ( $itemsWithCode as $item ) {
                if ($item->code) Cache::forget('menu.'.$item->code );
            }
        }
    }

	public function save( array $options = [] ) {

    	// reset rendered menu cache

        $this->resetMenuCache();

		return parent::save( $options );
	}

    public function delete()
    {
        $this->resetMenuCache();

        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
